// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVe9t76U9hGN-oxi684CclSdCZYz-qjjU',
    appId: '1:353453124863:web:761f0d377b58424639f0ca',
    messagingSenderId: '353453124863',
    projectId: 'notas-17ac2',
    authDomain: 'notas-17ac2.firebaseapp.com',
    storageBucket: 'notas-17ac2.firebasestorage.app',
    measurementId: 'G-2163MW9DK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpHVu3DQWECewhcgpuGB5ekwHuh-TW64',
    appId: '1:353453124863:android:4fd0710c3507676939f0ca',
    messagingSenderId: '353453124863',
    projectId: 'notas-17ac2',
    storageBucket: 'notas-17ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0YAjx1ZFxCR17ZJO6GUPgZAwk2TlZpsU',
    appId: '1:353453124863:ios:1d2c6b956149cd5439f0ca',
    messagingSenderId: '353453124863',
    projectId: 'notas-17ac2',
    storageBucket: 'notas-17ac2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4Notas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0YAjx1ZFxCR17ZJO6GUPgZAwk2TlZpsU',
    appId: '1:353453124863:ios:1d2c6b956149cd5439f0ca',
    messagingSenderId: '353453124863',
    projectId: 'notas-17ac2',
    storageBucket: 'notas-17ac2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4Notas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVe9t76U9hGN-oxi684CclSdCZYz-qjjU',
    appId: '1:353453124863:web:fd2dd56df3629e0339f0ca',
    messagingSenderId: '353453124863',
    projectId: 'notas-17ac2',
    authDomain: 'notas-17ac2.firebaseapp.com',
    storageBucket: 'notas-17ac2.firebasestorage.app',
    measurementId: 'G-L1YT4LK4VY',
  );
}
